include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    only_throw_errors: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_lambdas: true
    use_key_in_widget_constructors: true
